import * as moment from 'moment/moment';
export let guiaSadtAut30EmDig = {
  'totalCount': 20,
  'valorTotal': 14601.48,
  'codigosGuias': [904,
  905,
  1014,
  1015,
  1039,
  2504,
  2508,
  2520,
  2835,
  2736,
  2846,
  2853,
  2742,
  2743,
  2744,
  2745,
  2746,
  2747,
  2734,
  2735,
  1002],
  'numerosPedidos': [],
  'guias': [
    {
      'numeroPedido': '111618367',
      'dataConfirmacao': moment().add('days', -20).format(),
      'codigoGuia': '904',
      'numeroGuia': '123123',
      'numeroGuiaPrestador': '12099599',
      'lote': null,
      'codigoBeneficiario': '108963349',
      'beneficiario': 'JORGE LUIZ AVELINO DOS SANTOS',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 10.0,
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': '111618367',
      'dataConfirmacao': moment().add('days', -20).format(),
      'codigoGuia': '905',
      'numeroGuia': '11313',
      'numeroGuiaPrestador': '12099513',
      'lote': null,
      'codigoBeneficiario': '108963349',
      'beneficiario': 'JORGE LUIZ AVELINO DOS SANTOS',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': '121702964',
      'dataConfirmacao': moment().add('days', -15).format(),
      'codigoGuia': '1015',
      'numeroGuia': '0',
      'numeroGuiaPrestador': '12100650',
      'lote': null,
      'codigoBeneficiario': '070620881',
      'beneficiario': 'IGOR ARAUJO SILVA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 30.0,
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': '121702757',
      'dataConfirmacao': moment().add('days', -15).format(),
      'codigoGuia': '1039',
      'numeroGuia': '0',
      'numeroGuiaPrestador': '12101195',
      'lote': null,
      'codigoBeneficiario': '222333103',
      'beneficiario': 'ELZA NESTI PIMENTA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': null,
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': '2835',
      'numeroGuia': null,
      'numeroGuiaPrestador': '12102680',
      'lote': null,
      'codigoBeneficiario': '222333103',
      'beneficiario': 'ELZA NESTI PIMENTA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'codigoUsuarioInclusao': '10000399',
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': null,
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': '2736',
      'numeroGuia': null,
      'numeroGuiaPrestador': '12102744',
      'lote': null,
      'codigoBeneficiario': '222333103',
      'beneficiario': 'ELZA NESTI PIMENTA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 1.0,
      'codigoUsuarioInclusao': '10000399',
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': '121702757',
      'dataConfirmacao': moment().add('days', -15).format(),
      'codigoGuia': '1014',
      'numeroGuia': '0',
      'numeroGuiaPrestador': '12099800',
      'lote': null,
      'codigoBeneficiario': '222333103',
      'beneficiario': 'ELZA NESTI PIMENTA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': '111618367',
      'dataConfirmacao': moment().add('days', -15).format(),
      'codigoGuia': '2504',
      'numeroGuia': '0',
      'numeroGuiaPrestador': '12101660',
      'lote': null,
      'codigoBeneficiario': '108963349',
      'beneficiario': 'JORGE LUIZ AVELINO DOS SANTOS',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 15.0,
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': null,
      'dataConfirmacao': moment().add('days', -15).format(),
      'codigoGuia': '2508',
      'numeroGuia': null,
      'numeroGuiaPrestador': '12101700',
      'lote': null,
      'codigoBeneficiario': '222333103',
      'beneficiario': 'ELZA NESTI PIMENTA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': null,
      'dataConfirmacao': moment().add('days', -15).format(),
      'codigoGuia': '2520',
      'numeroGuia': null,
      'numeroGuiaPrestador': '12101897',
      'lote': null,
      'codigoBeneficiario': '630278431',
      'beneficiario': 'JHOCENI LEAL BARRETO',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': '121703042',
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': '2734',
      'numeroGuia': null,
      'numeroGuiaPrestador': '12102793',
      'lote': null,
      'codigoBeneficiario': '222333103',
      'beneficiario': 'ELZA NESTI PIMENTA',
      'tipoGuia': 'SADT',
      'situacao': 'DIGITADO',
      'valor': 13579.92,
      'codigoUsuarioInclusao': '10000399',
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },
    {
      'numeroPedido': '121703042',
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': '2735',
      'numeroGuia': null,
      'numeroGuiaPrestador': '12102741',
      'lote': null,
      'codigoBeneficiario': '222333103',
      'beneficiario': 'ELZA NESTI PIMENTA',
      'tipoGuia': 'SADT',
      'situacao': 'DIGITADO',
      'valor': 123.12,
      'codigoUsuarioInclusao': '10000399',
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },

    // SADT => ENVIADO => Digitada Automaticamente
    {
      'numeroPedido': '121702948',
      'dataConfirmacao': moment().add('days', -15).format(),
      'codigoGuia': '1002',
      'numeroGuia': '45589644',
      'numeroGuiaPrestador': '12099541',
      'lote': '1456',
      'codigoBeneficiario': '062305930',
      'beneficiario': 'CRISTIANE DA SILVA SANTOS',
      'tipoGuia': 'SADT',
      'situacao': 'ENVIADO',
      'valor': 297.0,
      'codigoUsuarioAlteracao': '10000399',
      'nomeUsuario': 'Bianca Bruna Amanda Souza',
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'NAO_POSSUI'
    },

    // SADT => DIGITADO => Digitada Automaticamente
    {
      'numeroPedido': '106459359',
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '106459359',
      'lote': null,
      'codigoBeneficiario': '107112647',
      'beneficiario': 'ANA PAULA RIBEIRO',
      'tipoGuia': 'SADT',
      'situacao': 'DIGITADO',
      'valor': 72.45,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    }, {
      'numeroPedido': '106228812',
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '106228812',
      'lote': null,
      'codigoBeneficiario': '107303728',
      'beneficiario': 'ROBERTO CALDAS BARCELAR',
      'tipoGuia': 'SADT',
      'situacao': 'DIGITADO',
      'valor': 72.45,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    }, {
      'numeroPedido': '106072447',
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '106072447',
      'lote': null,
      'codigoBeneficiario': '108568610',
      'beneficiario': 'ANGELA SALETE NICOLODI DURANTE VIEIRA',
      'tipoGuia': 'SADT',
      'situacao': 'DIGITADO',
      'valor': 72.45,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    }, {
      'numeroPedido': '106024189',
      'dataConfirmacao': moment().add('days', -10).format(),
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '106024189',
      'lote': null,
      'codigoBeneficiario': '107516993',
      'beneficiario': 'HAROLDO RODRIGUES DA COSTA',
      'tipoGuia': 'SADT',
      'situacao': 'DIGITADO',
      'valor': 72.45,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    },

    // SADT => NAO_DIGITADO => Digitada Automaticamente
    {
      'numeroPedido': '106079192',
      'dataConfirmacao': '2017-08-28T00:00:00',
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '106079192',
      'lote': null,
      'codigoBeneficiario': '107486245',
      'beneficiario': 'DEGILDO RODRIGUES ROSA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    }, {
      'numeroPedido': '105721063',
      'dataConfirmacao': '2017-08-28T00:00:00',
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '105721063',
      'lote': null,
      'codigoBeneficiario': '067511490',
      'beneficiario': 'RONALDO RODRIGUES CARMONA',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    }, {
      'numeroPedido': '105576351',
      'dataConfirmacao': '2017-08-28T00:00:00',
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '105576351',
      'lote': null,
      'codigoBeneficiario': '106960270',
      'beneficiario': 'RONALDO SAAD',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    }, {
      'numeroPedido': '105575637',
      'dataConfirmacao': '2017-08-28T00:00:00',
      'codigoGuia': null,
      'numeroGuia': null,
      'numeroGuiaPrestador': '105575637',
      'lote': null,
      'codigoBeneficiario': '107807670',
      'beneficiario': 'TANIA ROCHA DE AZEVEDO',
      'tipoGuia': 'SADT',
      'situacao': 'NAO_DIGITADO',
      'valor': 0.0,
      'tipoInclusao': 'Digitada Automaticamente',
      'possuiGlosa': false,
      'possuiCancelamento': false,
      'tipoGlosa': 'GUIA'
    }

  ]
};
