// <auto-generated />
namespace SearchByTag.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Start_Aplication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Start_Aplication));
        
        string IMigrationMetadata.Id
        {
            get { return "201802181706112_Start_Aplication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
